<Project>

  <PropertyGroup>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <PropertyGroup>
    <DefaultTargetFrameworkVersion>net9.0</DefaultTargetFrameworkVersion>
    <OrleansVersion>9.1.2</OrleansVersion>
    <Version>9.1.2</Version> 
  </PropertyGroup>

</Project>
